# Default Sourcery Configuration

# Version of the configuration file format
version: '1'

# Ignore files matching these patterns
ignore:
  - .git
  - node_modules
  - dist
  - build
  - '*.min.js'
  - '*.test.ts'
  - '*.test.tsx'

# Rule settings control which rules are run and their configuration
rule_settings:
  # List of rule IDs/tags Sourcery will exclusively suggest
  enable: [default]

  # List of rule IDs/tags Sourcery will never suggest
  disable: ['no-console-log', 'prefer-early-return']

  # Types of rules Sourcery will suggest
  rule_types:
    - refactoring
    - suggestion
    - comment
